### ISSUE TITLE
Demo Issue

### ISSUE THREAD

**Issue by DIVYANUNU** [vpriyapm/Project#3]
Issue format:[Example from soda project]
1.Issue/Feature Description:
After the installation (following https://docs.sodafoundation.io/soda-gettingstarted/quickstart/), the dashboard is not coming up.
Only blue background of dashboard is coming. No login options.

2.Why this issue to fixed / feature is needed(give scenarios or use cases):
Blocker for VirtualBox Ubuntu 18.04

3.How to reproduce, in case of a bug:
VirtualBox with Vanilla Ubuntu 18.04LTS, guest additions added.
Follow:
https://docs.sodafoundation.io/soda-gettingstarted/quickstart/

4.Other Notes / Environment Information: (Please give the env information, log link or any useful information for this issue)
VirtualBox 6.1 Version
Guest additions added
Installed Ubuntu 18.04 LTS vanilla
Faroe release with https://docs.sodafoundation.io/soda-gettingstarted/quickstart/

**Comment by vpriyapm** [comment]
Issue solved @DIVYANUNU
